version: "3.2"

services:
  entry:
    image: traefik:v2.10.4
    command:
    - --accesslog
    - --api.insecure
    - --providers.file.directory=/config
    - --entrypoints.websecure.address=:443
    - --entrypoints.websecure.http.tls
    volumes:
    - ./entry-config:/config
    ports:
    - "443:443"
    env_file:
      - .env

